# ===========================
# Namespace
# ===========================
apiVersion: v1
kind: Namespace
metadata:
  name: medical-apointment

---
# ===========================
# Backend Deployment
# ===========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: medical-apointment
  namespace: medical-apointment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medical-apointment
  template:
    metadata:
      labels:
        app: medical-apointment
    spec:
      containers:
        - name: medical-apointment
          image: your-dockerhub-username/medical-apointment:latest   # ⬅ replace with your image
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
---
apiVersion: v1
kind: Service
metadata:
  name: medical-apointment
  namespace: medical-apointment
spec:
  selector:
    app: medical-apointment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

---
# ===========================
# Frontend Deployment
# ===========================
apiVersion: apps/v1
kind: medical-apointment
metadata:
  name: medical-apointment
  namespace: medical-apointment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medical-apointment
  template:
    metadata:
      labels:
        app: medical-apointment
    spec:
      containers:
        - name: medical-apointment
          image: your-dockerhub-username/medical-apointment:latest   # ⬅ replace with your image
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: medical-apointment
  namespace: medical-apointment
spec:
  selector:
    app: medical-apointment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
# ===========================
# Ingress (Frontend + API)
# ===========================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: medical-apointment-ingress
  namespace: medical-apointment
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: medical-apointment.local    # ⬅ replace with your domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: medical-apointment
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: medical-apointment
                port:
                  number: 8080
